apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: random-value
spec:
  volumes:
  - name: sharedvolume
    emptyDir: {}
  - name: docker-sock-volume
    hostPath:
      path: /var/run/docker.sock
      type: File
  containers:
  - name: jnlp-slave
    image: aimvector/jenkins-slave
    command:
    - cat
    tty: true
    stdin: true
    volumeMounts:
    - mountPath: '/var/run/docker.sock'
      name: sharedvolume
  - name: jnlp-docker-slave
    image: aharonadav/alpine-docker:1
    command:
    - cat
    tty: true
    stdin: true
    volumeMounts:
    - mountPath: '/var/run/docker.sock'
      name: docker-sock-volume