apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
  name: alertmanager-templates
  namespace: {{ .Values.namespace }}
data:
  default.tmpl: |-
    none
---
kind: ConfigMap
apiVersion: v1
metadata:
  namespace: {{ .Values.namespace }}
  name: alertmanager
data:
{{ (.Files.Glob "config/alert.template").AsConfig | indent 2 }}
