apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: html
    app.kubernetes.io/instance: demo
  name: html
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: html
  type: ClusterIP
status:
  loadBalancer: {}
