---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: app1
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      serviceAccountName: app
      initContainers:
      - name: aws-cli
        image: amazon/aws-cli
        command: ["aws","s3","ls"]
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80