apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: custom.metrics.k8s.io
spec:
  service:
    name: custom-metrics-apiserver
    namespace: prometheus
  group: v1.custom.metrics.k8s.io
  version: v1beta1
  insecureSkipTLSVerify: true
  groupPriorityMinimum: 100
  versionPriority: 100
