---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: kubecost
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: "kubecost"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: kubecost-cost-analyzer
            port:
              number: 9090
