pipeline {
    agent {
     kubernetes {
      //cloud 'kubernetes'
      yamlFile 'KubernetesPod.yaml'
    }
  }
  stages {
      stage('Run shell') {
          steps {
              container('docker') {
                sh 'curl -LO "https://storage.googleapis.com/kubernetes-release/release/v1.20.5/bin/linux/amd64/kubectl"'  
                sh 'chmod u+x ./kubectl'  
                sh './kubectl get pods -n default'
              }
          }
      }
      stage('Run docker') {
          steps {
              container('docker') {
                  sh 'docker --version'
              }
          }
      }
  }
}