pipeline {
    agent {
     kubernetes {
      //cloud 'kubernetes'
      yamlFile 'KubernetesPod.yaml'
    }
  }
  stages {
      stage('Run shell') {
          steps {
            sh 'curl -LO "https://storage.googleapis.com/kubernetes-release/release/v1.20.5/bin/linux/amd64/kubectl"'  
            sh 'chmod u+x ./kubectl'  
            sh './kubectl get pods -n default'
          }  
      }
      stage('pull code') {
          steps {
              git branch: 'main',
                  credentialsId: 'aharon-github',
                  url: 'https://github.com/aharonadav/k8s.git'
              sh 'ls -lat'
          }
      }
      stage('Run docker') {
          steps {
              container('docker') {
                  sh 'docker --version'
              }
          }
      }
  }
}